### PR TITLE
del: barber deletion

### PR DESCRIPTION
**Pull request by Etrnlmelancholy**
## Описание

Removes the Barber role, removes barber related code, and removes safety scissors from the traitor pool item.
Thanks to FlitchTime for barbershop removal on maps

## Причина создания ПР / Почему это хорошо для игры

Ok ok, before everyone starts dropping their improve not removes and negative ratings on this PR, id like to at least pitch the idea first and give you some things to think about. An explanation why this role is so poorly designed and flawed.

Firstly,
its a bad role. I have constantly heard people use the defense of Barber being a """rp role""" in which its job is to make social interactions and roleplay as a barber. But I think that's a flawed argument, and it is very hollow when inspected closer. All roles are RP roles, you roleplay as the job you have chosen, and while some jobs are more dialogue oriented with others being more pressure focus, it is still roleplaying as the job you've chosen.

When you compare it to other roles barber lacks an actual excuse to exist alongside jobs that actually provide to the station. Security catches antagonist and works to enforce law, Chefs cook food and run kitchens and make dishes of variety, Doctors heal people, preform surgery, and provide medicine, etc etc. So what does Barber do? They cut hair. An incredibly niche, flawed, and boring field that is completely outclassed by a single object.

Secondly,
mirrors make the barber role obsolete. There is no question that everyone who has played or has experience knows that mirrors are the optimal way to get your hair back after any incident you lose them in. The process of going to a barber to get a haircut or something of the like is an issue of too many moving parts for something the mirror simplifies.

I have only seen people to go barbers either from being close friends with the player who cuts hair, or because its a green shift and people are bored out of their minds for anything to do. The issue with Barber's moving parts is the player themselves, and when it comes to getting your hair back most people do not want to spend five minutes with a player when they can do it in 10 seconds.

Thirdly,
there is zero content for barber. Like I've said previously, there is no depth or variety to the role, you simply cut hair and occasionally dye it. The only content most people know about is its traitor items, which are rather gimmicky in their purpose and serve more as surplus filler than anything else. For the years it has existed, the role has been a meme or joke of new players picking it and going around griefing people in the bar, or acting as just another assistant.

That issue stems from its lack of content, as its very fast and easy to get bored of such a role with absolutely no gameplay loop. There are a handful of people who try to make the most of barber but that pool is so tiny that is hard to justify keeping it for such a small count of people.

Lastly,
barbers history stems back January 16th, 2014 8:42 AM. In the same era when Paradise began and Karma was introduced into the game. Karma was flawed, and many of the roles that were Karma locked were and still are inherently flawed to the overall game. Either from being too incredibly niche, or lacking any sort of meaningful content. Barber is both those. And if people ask why we should remove it when we can optionally improve it, I ask. Why hasn't anyone bothered to improve this role for 10 YEARS?

It has been in a very similar state to its original design since 2014, and not a single person during the many eras of Paradise has bothered to make it all interesting or meaningful. I think we are past that time, and instead of preaching a non productive mantra, we should do what is healthy for the game and remove poor, badly designed bloats job from a younger era of Paradise, just like Karma.

As a great host once said, that I absolutely agree with, quote,

aa07 | Im competent I promise — 03/01/2022 11:45 AM
barber is the perfect example of a role that was shoehorned in
it has no purpose

https://discord.com/channels/617003227182792704/755125334097133628/1318669846652649534

## Демонстрация изменений

image

## Тесты

image
image

### CODE REVIEW

**Comment by Etrnlmelancholy** [comment]
OctusGit герой

**Comment by FlitchTime** [comment]
Копипаста пасты :GAGAGA

**Comment by SAADf603** [comment]
AA07 be like
image

**Review by SAADf603 — DISMISSED** [review]

**Review by Daeberdir — CHANGES_REQUESTED** [review]
Вернуть лендмарки, вернуть код роли, но вывести из джобок.

**Comment by Etrnlmelancholy** [comment]
Нет, иди нахуй
image

**Comment by Daeberdir** [comment]
Либо делаешь нормально, либо не делаешь.

**Comment by Etrnlmelancholy** [comment]
High command told me to do it the other way, поэтому свои хотелки можешь запихнуть себе в очко, тупорылый дегенерат с завышенным чувством собственного достоинства 
image

**Comment by BeebBeebBoob** [comment]
> Вернуть лендмарки, вернуть код роли, но вывести из джобок.

Либо читаешь предложу сперва и условия либо не проверяй вовсе.
Сказано, удалить все к хуям, значит все. И лендмарки и другие Барбер вещи связанные.
Отменяю вето. Let the man cook PR.

**Review by SAADf603 — APPROVED** [review]

**Comment by SAADf603** [comment]
На всякий поясню: удалять барбер зону пока не стоит, потому что ивент карты всё ещё остаются с комнатой барбера. Я исправлю это позже в рефакторе зон

**Review by BeebBeebBoob — APPROVED** [review]

**Pull request merged**
